const express=require("express")
require('dotenv').config()
const app=express()
app.use(express.json())
const  department=require("./Routes/deparment_rout")
const categories=require("./Routes/categories")
const attribute=require("./Routes/attributes")
const product=require('./Routes/products')
const customer=require("./Routes/customer")
const order=require("./Routes/order")
const shoppingcart=require("./Routes/shoppingcart")
const tax=require("./Routes/tax")
const shipping=require("./Routes/shipping")
// const custo=require("./router/cust")
app.use('/',department,attribute,categories,product,customer,order,shoppingcart,tax,shipping)
app.listen(process.env.APP_PORT,()=>{
    console.log("listen port:",process.env.APP_PORT)
})